Build HDivConstant, HDivKernel and HCurlNoGrads approximation spaces
labmec/neopz pull request #143
Opened 2022-02-02 02:25 UTC by jefersondossa

In this PR the TPZCreateApproxSpace environment was updated to build HDivConstant, HDivKernel (HDivFamily) and HCurlNoGrads (HCurlFamily) approximation spaces.

Main changes:
- The HDivConstant computational element is now part of the TPZCompElHDiv;
- HDivKernel and HCurlNoGrads are computational elements derived from TPZCompElHCurl. The only difference between them is how the H1 grads are removed from the approximation space: hardcoded for HDivKernel and analytically removed for HCurlNoGrads;
- TPZCompElHCurlNoGrads and TPZCompElHDivConstant were removed;
- The desired approximation space can be built with SetAllCreateFunctionsHDiv or SetAllCreateFunctionsHCurl, chosing the proper HDivFamily or HCurlFamily, respectively.

2022-02-02 12:26 UTC, orlandini commented on Mesh/TPZHCurlEquationFilter.h
> +    bool FilterEdgeEquations(TPZCompMesh* cmesh, TPZVec<int64_t> &activeEquations, bool &domainHybridization);
this line made me learn this: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-smart

thank you!

2022-02-02 12:50 UTC, orlandini reviewed
I think that there are many things to discuss related to #122 , #139 and #140

2022-02-02 12:50 UTC, orlandini commented on Mesh/pzcreateapproxspace.h
>  //    void SetAllCreateFunctionsHDivFull(int meshdim);
Doesn't this go against  2ffec98 ? I think we need to discuss this thoroughly

2022-02-02 12:50 UTC, orlandini commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +    this->~TPZCompElHCurl<TSHAPE>();
There is no need to call the parent's destructor explicitly

2022-02-02 12:50 UTC, orlandini commented on Mesh/TPZCompElKernelHDiv3D.h
> +    HDivFamily fhdivfam = DefaultFamily::fHDivDefaultValue;
this is a bit confusing.. is there a need to keep the harcoded version?

2022-02-02 12:50 UTC, orlandini commented on Mesh/TPZCompElKernelHDiv3D.h
>  protected:
In my opinion, this goes against #122 .

By changing TPZCompElHCurl<TSHAPE>::NConnectShapeF(int,int) to something like this:


```c++
template<class TSHAPE>
int TPZCompElHCurl<TSHAPE>::NConnectShapeF(int connect, int order) const
{
  switch(hcurlfam){
  case EHCurlStandard:
  return TPZShapeHCurl<TSHAPE>::ComputeNConnectShapeF(connect, order);
  case EHCurlNoGrads:
  return TPZShapeHCurlNoGrads<TSHAPE>::ComputeNConnectShapeF(connect,order);
  }
}
  ```

  this method wouldn't even be needed. Right?
  
  If this is correct, this applies to most of this class.

2022-02-02 12:50 UTC, orlandini commented on Mesh/TPZCompElKernelHDivBC3D.h
>  template<class TSHAPE>
Is this class necessary? if so, why?

2022-02-02 12:50 UTC, orlandini commented on Mesh/TPZCompElKernelHDivBC3D.cpp
> +            since there are (k-1)(k-2)(k-3)/6 functions in a h1 element with order k,
how can a BC element be a 3d el?

2022-02-02 12:50 UTC, orlandini commented on Mesh/pzelchdiv.cpp
There is a LOT of initialization going on here... Is it really needed?

2022-02-02 13:10 UTC, jefersondossa commented on Mesh/pzcreateapproxspace.h
>  //    void SetAllCreateFunctionsHDivFull(int meshdim);
You are right, I think I missed something here because the original idea was to pick the Approximation space family as a parameter of SetAllCreateFunctionsXXX.

2022-02-02 13:25 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +    this->~TPZCompElHCurl<TSHAPE>();
Removed from the code.

2022-02-02 13:49 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDivBC3D.h
>  template<class TSHAPE>
You are right. This class can be removed once TPZCompElKernelHDiv can deal with both domain and BC CompEls.

2022-02-02 13:49 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDivBC3D.cpp
> +            since there are (k-1)(k-2)(k-3)/6 functions in a h1 element with order k,
The class will be removed.

2022-02-02 14:07 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
Initialization refactored.

2022-02-02 14:21 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
I refactored this part of the code. All those initialization were not needed.

2022-02-02 14:34 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
This initialization is needed since we have HCurl functions being set to an HDiv CompEl.

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv.cpp
> +    if (TSHAPE::Type() == ETriangle && connect == 6) order++;
In 2D, the KernelHDiv computes the Ker(phi).n, does it not? Then please comment on this method. Does the NConnectShapeF really correspond to the number of H1 shape functions?

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv.cpp
> +template<class TSHAPE>
Please include comment statements. What does the method do, which methods call this method

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv.cpp
>  #include "pzshapelinear.h"
Porque esse "monte" de includes?

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv.h
> -    int fSideOrient = 1;
There is no sideorient for KernelHDiv. Where is it used?

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +    if (fhdivfam != HDivFamily::EHDivKernel && fhdivfam != HDivFamily::EHCurlNoGrads){
What is the meaning of HDivFamily::EHCurlNoGrads? HCurlNoGrads is an hcurl type approximation space?

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +    case HDivFamily::EHCurlNoGrads:
Why would an HDiv element compute HCurl functions?

2022-03-05 02:25 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv3D.h
> +    HDivFamily fhdivfam = DefaultFamily::fHDivDefaultValue;
In the KernelHDiv3D we don't have different options. There is no need to fShapeType

2022-03-05 02:29 UTC, philippedevloo commented on Mesh/TPZCompElKernelHDiv3D.h
>  protected:
I believe the HDivKernel3D derived class only "deals with" HDiv functions. HCurlNoGrads is a HCurl class. Actually it is an option of the HCurl class

2022-03-05 02:35 UTC, philippedevloo commented on Mesh/pzelchdiv.cpp
Agreed with Fran. I don't understand why there isnt a switch statement for calling InitMaterialData for the different flavors of HDiv. HDivConstant has a different number of shape functions, operates differently...

2022-03-05 14:06 UTC, philippedevloo requested changes
Many of my comments require changes. Lets schedule a meeting to discuss this

2022-03-05 14:06 UTC, philippedevloo commented on Topology/tpzline.h
> +            DebugStop();
Why DebugStop? The linear shape function has constant divergence

2022-03-05 14:06 UTC, philippedevloo commented on UnitTest_PZ/TestMesh/TestKernelHDiv.cpp
> -#include "TPZCompElHDivConstant.h"
Which unit test verifies HDivConstant?

2022-03-07 19:50 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv.cpp
>  #include "pzshapelinear.h"
They are not needed and are going to be removed.

2022-03-07 20:01 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
You are right. This version is outdated. After this discussion I changed the version and removed all the unnecessary initialization.

2022-03-07 20:04 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv.cpp
> +void TPZCompElKernelHDiv<TSHAPE>::SetSideOrient(int side, int sideorient){
There is no need for side orient in this element. Removing.

2022-03-07 20:04 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv.h
> -    int fSideOrient = 1;
It is not used. Removing.

2022-03-08 13:17 UTC, jefersondossa commented on Shape/TPZShapeHDivKernel2D.cpp
>      divphi.Zero();
Removed

2022-03-08 13:20 UTC, jefersondossa commented on Shape/TPZShapeHDivKernel.cpp
>          data.fHDivNumConnectShape[iedge] = 2;
The class was removed as hardcoded filtered functions are no longer used.

2022-03-08 13:20 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.h
>      TPZManVector<int, TSHAPE::NFacets> fSideOrient;
Deleted.

2022-03-08 13:25 UTC, jefersondossa commented on Mesh/pzcreateapproxspace.cpp
> +    if (fhdivfam == HDivFamily::EHDivKernel || fhdivfam == HDivFamily::EHCurlNoGrads){
Removed

2022-03-08 23:49 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant){
Removed.

2022-03-13 15:33 UTC, philippedevloo requested changes
There are some methods that need adjustment. I put comments in all places that need to be fixed

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdiv.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant) {
Is this necessary?

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdiv.cpp
>              ivec    = data.fVecShapeIndex[counter].first;
As fVecShapeIndex is not used anymore, we should delete its use from "internal" methods

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdiv.cpp
> +        TPZShapeHDivConstant<TSHAPE>::Initialize(ids, orders, data);
As HDivConstante still depends on the orientation of the constant flux, sideorient should be part of its constructor

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdiv.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant){
I dont think this order increase is necessary? MaxOrder is used to determine the order of the integration rule. The order of the HDiv functions are order+1 for all topologies

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdiv.h
> +    /// Return the maximum order
Return the maximum order of the HDiv functions

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant) {
Is this necessary? Include motivation in a comment section or delete

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
> +        if(connect == 0)
Please respond the observation above...

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
> +    default:
In other classes the default was not handled on purpose. Why is it handled here?

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
>      if (fSideOrient == -1) {
The sideorient should be applied only to the first function for HDivConstant

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
>      mesh->SetAllCreateFunctionsHDiv();
But you have to specify in the approximation space which hdiv family corresponds to this element

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzelchdivbound2.cpp
> +        case ETriangle:
This is not the case for the boundary fluxes

2022-03-13 15:33 UTC, philippedevloo commented on Mesh/pzinterpolationspace.cpp
Maybe we should discuss this? Who is responsible for taking the absolute value?

2022-03-13 15:33 UTC, philippedevloo commented on Topology/tpzquadrilateral.cpp
Maybe delete the transformationid argument?

2022-03-13 22:49 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv.cpp
>                  data.sol[0][dim*idf+0] -= meshsol * dphix(1,ishape);
Chaged. Now the solution is computed using fDeformedDirections.

2022-03-13 22:51 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.h
> +    /// Family of the HDiv space being used. Only HDivFamily::EHDivKernel and HDivFamily::EHCurlNoGrads are supported
Comment fixed.

2022-03-13 22:53 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.h
> +    return Hash("TPZCompElKernelHDiv3D") ^ TPZCompElHCurl<TSHAPE>::ClassId() << 1;
Because now there is no more TPZCompElHCurlNoGrads, as EHCurlNoGrads is an HCurlFamily, set as input in TPZCompElHCurl

2022-03-13 22:55 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.h
> +/** @brief Creates computational point element for HDivKernel approximate space */
No.  Actually 2D and 3D versions of HDivKernel were being created in the same place. I moved the creators of 2D elements to TPZCompElKernelHDiv.cpp.

2022-03-13 23:01 UTC, jefersondossa commented on Mesh/pzcreateapproxspace.cpp
> +            case 2:
Fixed

2022-03-13 23:02 UTC, jefersondossa commented on Mesh/pzcreateapproxspace.cpp
> +    } else {
Comment added

2022-03-13 23:03 UTC, jefersondossa commented on Mesh/pzcreateapproxspace.cpp
> +                fp[ETriangle] = [hdivfam](TPZGeoEl *gel,TPZCompMesh &mesh) {return CreateHDivTriangleEl(gel,mesh,hdivfam);};
Fixed. CreateHDivTriangleEl changed to CreateNoElement

2022-03-13 23:11 UTC, jefersondossa commented on Topology/tpzquadrilateral.cpp
Removed the transformationId argument of all topologies.

2022-03-13 23:28 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.h
>      mesh->SetAllCreateFunctionsContinuous();
Fixed the method.

2022-03-13 23:35 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +        data.fDeformedDirections.Resize(3,nshape);
I checked and the dimensions are correct. I also removed all redim/resize in ComputeShape method.

2022-03-13 23:37 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.cpp
> +        for (int j = 0; j < nshape; j++){
Moved

2022-03-13 23:41 UTC, jefersondossa commented on Mesh/TPZCompElKernelHDiv3D.cpp
>          std::stringstream sout;
Deleted. It was there just to print some vector information. Not needed anymore.

2022-03-13 23:47 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant) {
Yes. Since we compatibilized the polynomial order with connectOrders, the number of shape functions of each connect as well as the integration rule need to be updated. The comment in line 93 didn't made sense anymore in this context so I removed it.

2022-03-13 23:52 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
> +        TPZShapeHDivConstant<TSHAPE>::Initialize(ids, orders, data);
Fixed

2022-03-13 23:58 UTC, jefersondossa commented on Mesh/pzelchdiv.h
> +    /// Return the maximum order
Fixed

2022-03-13 23:58 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
>              ivec    = data.fVecShapeIndex[counter].first;
Deleted

2022-03-14 00:21 UTC, jefersondossa commented on Mesh/pzelchdiv.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant){
The tests passed using only order+1, but I'm not sure if it is right since for triangles and tetrahedra we need order+2. I keep it unchanged by now, so we talk about it.

2022-03-14 00:24 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
> +    if (fhdivfam == HDivFamily::EHDivConstant) {
Same as TPZCompElHDiv. As we changed the connect polynomial order in TPZShapeHDivConstant<TSHAPE>::Initialize, we need to update the number of shape functions and the integration rule.

2022-03-14 00:33 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
> +        if(connect == 0)
Deleted the switch structure.

2022-03-14 00:36 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
> +    default:
In TPZCompElHDiv we did the same for the Initialization of TPZShapeData

2022-03-14 00:39 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
>      if (fSideOrient == -1) {
Fixed. Changed to phi(0,0) and dphi(0,0)

2022-03-14 00:40 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
>      mesh->SetAllCreateFunctionsHDiv();
Fixed

2022-03-14 00:43 UTC, jefersondossa commented on Mesh/pzelchdivbound2.cpp
> +        case ETriangle:
Method MaxOrder removed

2022-03-14 00:47 UTC, jefersondossa commented on Mesh/pzinterpolationspace.cpp
For HDiv elements, the absolute value is taken in ComputeShape. For the other elements we also need to take the absolute value, as they will break if we have negative Jacobians (at least for HCurl-derived)?

2022-03-18 18:01 UTC, merged